### ISSUE TITLE
pb lancement moteur

### ISSUE THREAD

**Issue by AriiPortal** [AriiPortal/symfony-arii-edition#1]
Bonjour,
Une fois Arii en foncitonnement (tous les points de c:\arii check sont à OK), j'ai tenté de démarrer le moteur superviseur (c:\ arii start_supervisor) sans succès. En pj, une copie d'écran du message d'erreur dans ll log. 
jf

![capture d ecran 2017-10-19 a 10 19 53](https://user-images.githubusercontent.com/10708168/31762128-8aa681e0-b4ba-11e7-80b2-5e16fdf8b7c2.png)

**Comment by jfpace** [comment]
ps : le fichier dll est bien présent : 
![capture d ecran 2017-10-19 a 11 08 11](https://user-images.githubusercontent.com/17028741/31763195-dd07818e-b4bd-11e7-9e88-9912d763a153.png)

**Comment by AriiPortal** [comment]
Bonjour,

Je vois 2 soucis:
- le jobscheduler est en 64bits, il faut vérifier la version dans le log:
`.19 16:03:50.389 scheduler    0  5544.CD8  50.160MB Compiler Microsoft Visual C++ 12.0  (1800), Nov  4 2016, 32bit`
et non
`.19 15:11:10.497 scheduler    0  7164.114C 53.066MB Compiler Microsoft Visual C++ 12.0  (1800), Nov  4 2016, 64bit`
- ensuite le JAVA_HOME ne semble pas suffisant pour forcer la version java embarquée, dans ce cas on modifie le sos.ini comme suit:
```
[java]
;                         does not necessarily work, use PATH (Windows) or LD_LIBRARY_PATH (Unix) to locate the Java VM
vm                     =  ${JAVA_HOME}\bin\client\jvm.dll
```

Je modifie la version portable en conséquence.

Bonne journée, 
Eric
